project:
  type: website
  output-dir: docs

website:
  title: "brian leung"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/leungkp
format:
  html:
    theme: 
      primary: mystyles.scss

editor: visual

